persistence true
persistence_location /mosquitto/data/

allow_anonymous false
password_file /mosquitto/config/passwords

listener 9001 0.0.0.0
protocol websockets

connection_messages true
log_type error
log_type warning
log_type notice
