#!/usr/bin/env python3
from pathlib import Path
import shutil
import subprocess
import tempfile

root = Path(__file__).resolve().parents[1]
kotlinc = shutil.which('kotlinc')
if not kotlinc:
    raise SystemExit('kotlinc is required')
coroutines = Path('/root/.sdkman/candidates/kotlin/1.9.0/lib/kotlinx-coroutines-core-jvm.jar')
if not coroutines.is_file():
    raise SystemExit(f'kotlinx-coroutines-core-jvm.jar missing: {coroutines}')

STUBS = {
    'AndroidManifest.kt': '''package android\nobject Manifest { object permission { const val CAMERA="CAMERA"; const val NEARBY_WIFI_DEVICES="NEARBY_WIFI_DEVICES"; const val ACCESS_FINE_LOCATION="ACCESS_FINE_LOCATION" } }\n''',
    'AndroidContent.kt': '''package android.content\nopen class Context { companion object { const val MODE_PRIVATE=0; const val NSD_SERVICE="servicediscovery" }; open val applicationContext:Context get()=this; open fun getSystemService(name:String):Any=android.net.nsd.NsdManager(); open fun <T> getSystemService(clazz:Class<T>):T=clazz.getDeclaredConstructor().newInstance(); open fun getSharedPreferences(name:String,mode:Int)=SharedPreferences() }\nclass SharedPreferences { fun getString(key:String,default:String?):String?=default; fun getBoolean(key:String,default:Boolean)=default; fun edit()=Editor(); class Editor { fun putString(key:String,value:String?):Editor=this; fun putBoolean(key:String,value:Boolean):Editor=this; fun remove(key:String):Editor=this; fun apply(){} } }\n''',
    'AndroidPackageManager.kt': '''package android.content.pm\nobject PackageManager { const val PERMISSION_GRANTED=0 }\n''',
    'AndroidOs.kt': '''package android.os\nopen class Bundle\nobject Build { object VERSION { const val SDK_INT=35 }; object VERSION_CODES { const val Q=29; const val TIRAMISU=33 } }\n''',
    'AndroidNet.kt': '''package android.net\nclass Uri private constructor(val scheme:String?="homeguard",val host:String?="provision") { companion object { fun parse(raw:String)=Uri() }; fun getQueryParameter(name:String):String?="value" }\nopen class Network\nopen class NetworkCapabilities { companion object { const val TRANSPORT_WIFI=1; const val NET_CAPABILITY_INTERNET=2 } }\nclass NetworkRequest { class Builder { fun addTransportType(value:Int)=this; fun removeCapability(value:Int)=this; fun setNetworkSpecifier(value:Any)=this; fun build()=NetworkRequest() } }\nopen class ConnectivityManager { open class NetworkCallback { open fun onAvailable(network:Network){}; open fun onUnavailable(){} }; fun bindProcessToNetwork(network:Network?):Boolean=true; fun requestNetwork(request:NetworkRequest,callback:NetworkCallback,timeoutMs:Int){}; fun unregisterNetworkCallback(callback:NetworkCallback){} }\n''',
    'AndroidWifi.kt': '''package android.net.wifi\nclass WifiNetworkSpecifier { class Builder { fun setSsid(value:String)=this; fun setWpa2Passphrase(value:String)=this; fun build()=WifiNetworkSpecifier() } }\n''',
    'AndroidNsd.kt': '''package android.net.nsd\nimport java.net.InetAddress\nopen class NsdServiceInfo { var attributes:Map<String,ByteArray> = emptyMap(); var serviceName:String=""; var host:InetAddress?=null; var port:Int=443; var serviceType:String="" }\nopen class NsdManager { companion object { const val PROTOCOL_DNS_SD=1 }; interface ResolveListener { fun onResolveFailed(serviceInfo:NsdServiceInfo,errorCode:Int); fun onServiceResolved(serviceInfo:NsdServiceInfo) }; interface DiscoveryListener { fun onDiscoveryStarted(serviceType:String); fun onStartDiscoveryFailed(serviceType:String,errorCode:Int); fun onStopDiscoveryFailed(serviceType:String,errorCode:Int); fun onDiscoveryStopped(serviceType:String); fun onServiceFound(serviceInfo:NsdServiceInfo); fun onServiceLost(serviceInfo:NsdServiceInfo) }; fun resolveService(info:NsdServiceInfo,listener:ResolveListener){}; fun discoverServices(type:String,protocol:Int,listener:DiscoveryListener){}; fun stopServiceDiscovery(listener:DiscoveryListener){} }\n''',
    'AndroidKeystore.kt': '''package android.security.keystore\nimport java.security.spec.AlgorithmParameterSpec\nclass KeyGenParameterSpec:AlgorithmParameterSpec { class Builder(val alias:String,val purposes:Int) { fun setBlockModes(vararg value:String)=this; fun setEncryptionPaddings(vararg value:String)=this; fun setKeySize(value:Int)=this; fun build()=KeyGenParameterSpec() } }\nobject KeyProperties { const val KEY_ALGORITHM_AES="AES"; const val PURPOSE_ENCRYPT=1; const val PURPOSE_DECRYPT=2; const val BLOCK_MODE_GCM="GCM"; const val ENCRYPTION_PADDING_NONE="NoPadding" }\n''',
    'AndroidBase64.kt': '''package android.util\nimport java.util.Base64 as JBase64\nobject Base64 { const val NO_WRAP=1; const val URL_SAFE=2; const val NO_PADDING=4; fun encodeToString(bytes:ByteArray,flags:Int)=JBase64.getUrlEncoder().withoutPadding().encodeToString(bytes); fun decode(value:String,flags:Int)=JBase64.getUrlDecoder().decode(value) }\n''',
    'ActivityResult.kt': '''package androidx.activity.result\nopen class ActivityResultContract<I,O>\nclass ActivityResultLauncher<I> { fun launch(input:I){} }\n''',
    'ActivityContracts.kt': '''package androidx.activity.result.contract\nimport androidx.activity.result.ActivityResultContract\nobject ActivityResultContracts { class RequestMultiplePermissions:ActivityResultContract<Array<String>,Map<String,Boolean>>() }\n''',
    'Activity.kt': '''package androidx.activity\nimport android.content.Context\nimport android.os.Bundle\nimport androidx.activity.result.ActivityResultContract\nimport androidx.activity.result.ActivityResultLauncher\nopen class ComponentActivity:Context() { open fun onCreate(savedInstanceState:Bundle?){}; open fun onDestroy(){}; fun <I,O> registerForActivityResult(contract:ActivityResultContract<I,O>,callback:(O)->Unit):ActivityResultLauncher<I> = ActivityResultLauncher() }\n''',
    'ActivityCompose.kt': '''package androidx.activity.compose\nimport androidx.activity.ComponentActivity\nimport androidx.compose.runtime.Composable\nfun ComponentActivity.setContent(content:@Composable ()->Unit){content()}\n''',
    'ContextCompat.kt': '''package androidx.core.content\nimport android.content.Context\nobject ContextCompat { fun checkSelfPermission(context:Context,permission:String)=0 }\n''',
    'Lifecycle.kt': '''package androidx.lifecycle\nimport androidx.activity.ComponentActivity\nimport kotlinx.coroutines.CoroutineScope\nimport kotlinx.coroutines.Dispatchers\nimport kotlinx.coroutines.SupervisorJob\nopen class ViewModel\nval ViewModel.viewModelScope:CoroutineScope get()=CoroutineScope(SupervisorJob()+Dispatchers.Default)\nval ComponentActivity.lifecycleScope:CoroutineScope get()=CoroutineScope(SupervisorJob()+Dispatchers.Default)\n''',
    'ComposeRuntime.kt': '''package androidx.compose.runtime\nimport kotlin.reflect.KProperty\nimport kotlinx.coroutines.flow.Flow\nimport kotlinx.coroutines.flow.StateFlow\n@Target(AnnotationTarget.FUNCTION,AnnotationTarget.TYPE) annotation class Composable\nopen class State<T>(open val value:T)\nclass MutableState<T>(override var value:T):State<T>(value)\noperator fun <T> State<T>.getValue(thisObj:Any?,property:KProperty<*>):T=value\noperator fun <T> MutableState<T>.setValue(thisObj:Any?,property:KProperty<*>,value:T){this.value=value}\nfun <T> mutableStateOf(value:T)=MutableState(value)\nfun <T> remember(block:()->T)=block()\nfun <T> StateFlow<T>.collectAsState():State<T> = State(value)\nfun <T> Flow<T>.collectAsState(initial:T):State<T> = State(initial)\n''',
    'ComposeUi.kt': '''package androidx.compose.ui\nopen class Modifier { companion object:Modifier() }\n''',
    'ComposeUnit.kt': '''package androidx.compose.ui.unit\ndata class Dp(val value:Int)\nval Int.dp:Dp get()=Dp(this)\n''',
    'ComposeTextInput.kt': '''package androidx.compose.ui.text.input\nobject KeyboardType { val Password=Any() }\nclass PasswordVisualTransformation\n''',
    'ComposeKeyboard.kt': '''package androidx.compose.foundation.text\nclass KeyboardOptions(val keyboardType:Any?=null)\n''',
    'ComposeLayout.kt': '''package androidx.compose.foundation.layout\nimport androidx.compose.runtime.Composable\nimport androidx.compose.ui.Modifier\nimport androidx.compose.ui.unit.Dp\nobject Arrangement { fun spacedBy(value:Dp):Any=Any() }\nfun Modifier.fillMaxSize():Modifier=this\nfun Modifier.fillMaxWidth():Modifier=this\nfun Modifier.padding(value:Dp):Modifier=this\n@Composable fun Column(modifier:Modifier=Modifier,verticalArrangement:Any?=null,content:@Composable ()->Unit){content()}\n@Composable fun Row(modifier:Modifier=Modifier,content:@Composable ()->Unit){content()}\n''',
    'Material3.kt': '''package androidx.compose.material3\nimport androidx.compose.runtime.Composable\nimport androidx.compose.ui.Modifier\nobject MaterialTheme { val typography=Typography(); @Composable operator fun invoke(content:@Composable ()->Unit){content()} }\nclass Typography { val headlineSmall:Any=Any() }\n@Composable fun Text(text:String,style:Any?=null){}\n@Composable fun Button(onClick:()->Unit,enabled:Boolean=true,content:@Composable ()->Unit){content()}\n@Composable fun CircularProgressIndicator(){}\n@Composable fun OutlinedTextField(value:String,onValueChange:(String)->Unit,label:@Composable ()->Unit,modifier:Modifier=Modifier,visualTransformation:Any?=null,keyboardOptions:Any?=null){label()}\n@Composable fun AssistChip(onClick:()->Unit,label:@Composable ()->Unit){label()}\n@Composable fun Card(content:@Composable ()->Unit){content()}\n@Composable fun ListItem(headlineContent:@Composable ()->Unit,supportingContent:@Composable ()->Unit={}){headlineContent();supportingContent()}\n''',
    'Zxing.kt': '''package com.journeyapps.barcodescanner\nimport androidx.activity.result.ActivityResultContract\nclass ScanIntentResult(val contents:String?)\nclass ScanContract:ActivityResultContract<ScanOptions,ScanIntentResult>()\nclass ScanOptions { fun setPrompt(value:String)=this; fun setBeepEnabled(value:Boolean)=this; fun setOrientationLocked(value:Boolean)=this }\n''',
    'OkHttp.kt': '''package okhttp3\nimport java.io.Closeable\nimport java.io.IOException\nimport java.time.Duration\nimport javax.net.ssl.SSLSocketFactory\nimport javax.net.ssl.X509TrustManager\nclass MediaType { companion object { fun String.toMediaType()=MediaType() } }\nopen class RequestBody { companion object { fun String.toRequestBody(mediaType:MediaType)=RequestBody() } }\nclass Request { class Builder { fun url(value:String)=this; fun header(name:String,value:String)=this; fun post(body:RequestBody)=this; fun build()=Request() } }\nclass ResponseBody { fun string():String="" }\nopen class Response:Closeable { val body:ResponseBody?=ResponseBody(); val isSuccessful=true; val code=200; override fun close(){} }\ninterface Callback { fun onFailure(call:Call,error:IOException); fun onResponse(call:Call,response:Response) }\ninterface Call { fun enqueue(callback:Callback); fun cancel(); fun execute():Response }\ninterface WebSocket { fun close(code:Int,reason:String?):Boolean }\nopen class WebSocketListener { open fun onMessage(webSocket:WebSocket,text:String){}; open fun onFailure(webSocket:WebSocket,t:Throwable,response:Response?){}; open fun onClosed(webSocket:WebSocket,code:Int,reason:String){} }\nclass OkHttpClient { class Builder { fun callTimeout(duration:Duration)=this; fun sslSocketFactory(factory:SSLSocketFactory,trustManager:X509TrustManager)=this; fun build()=OkHttpClient() }; fun newCall(request:Request):Call=object:Call { override fun enqueue(callback:Callback){}; override fun cancel(){}; override fun execute()=Response() }; fun newWebSocket(request:Request,listener:WebSocketListener):WebSocket=object:WebSocket { override fun close(code:Int,reason:String?)=true } }\n''',
    'Json.kt': '''package org.json\nclass JSONArray { fun length()=0; fun getJSONObject(index:Int)=JSONObject() }\nclass JSONObject { constructor(); constructor(text:String); fun put(key:String,value:Any?):JSONObject=this; fun optBoolean(key:String,default:Boolean=false)=default; fun optString(key:String,default:String="")=default; fun optInt(key:String,default:Int=0)=default; fun optLong(key:String,default:Long=0)=default; fun optDouble(key:String,default:Double=0.0)=default; fun getLong(key:String)=0L; fun optJSONArray(key:String):JSONArray?=null; override fun toString()="{}" }\n''',
    'BuildConfig.kt': '''package ua.homeguard.s3\nobject BuildConfig { const val VERSION_NAME="0.0.13" }\n''',
}

with tempfile.TemporaryDirectory(prefix='homeguard-kotlin-full-') as temporary:
    temp = Path(temporary)
    stub_files = []
    for name, text in STUBS.items():
        path = temp / name
        path.write_text(text, encoding='utf-8')
        stub_files.append(path)
    sources = sorted((root / 'android/app/src/main/java').rglob('*.kt'))
    output = temp / 'homeguard-android-full-check.jar'
    subprocess.run([
        kotlinc,
        '-J-Dkotlin.daemon.enabled=false',
        '-J-Dkotlin.compiler.execution.strategy=in-process',
        '-classpath', str(coroutines),
        *map(str, stub_files + sources),
        '-d', str(output),
    ], check=True)
print(f'HomeGuard Android full source compile: {len(sources)} files PASS')
